package transfers;

public interface TypeRequestAnswer {
    String ERROR = "ERROR";
    String AUTHORIZATION = "AUTHORIZATION";
    String AUTHORIZATION_DONE = "AUTHORIZATION_DONE";
    String AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE";
    String USER_NOT_EXIST = "USER_NOT_EXIST";
    String WRONG_PASSWORD = "WRONG_PASSWORD";
    String REGISTRATION = "REGISTRATION";
    String REGISTRATION_DONE = "REGISTRATION_DONE";
    String USER_ALREADY_EXIST = "USER_ALREADY_EXIST";
    String BAD_LOGIN = "BAD_LOGIN";
    String BAD_PASSWORD = "BAD_PASSWORD";
    String GET_FRIENDS = "GET_FRIENDS";
    String ADD_FRIEND = "ADD_FRIEND";
    String REQUEST_SENT = "REQUEST_SENT";
    String GET_REQUEST_IN = "GET_REQUEST_IN";
    String GET_MESSAGES = "GET_MESSAGES";
    String NEW_MESSAGE = "NEW_MESSAGE";
}
